# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.15.4
      - name: Install node-modules and build
        run: yarn install && yarn build
          
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
          
      - name: Install crusher-cli
        run: npm install -g crusher-cli@1.3.35
        
      - name: Start crusher tests
        run: crusher-cli run --project_id=112  --crusher_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMjgsInRlYW1faWQiOjg1LCJpYXQiOjE2MTM2Njc5MzQsImV4cCI6NTIxMzY2NDMzNH0.9fQUSNQ12lYVRK9O_5_Zxm0Pm1RFJCifvcUdQFzdo-0 

