# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.15.4
      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          deploy_alias: ${{ env.BRANCH_NAME }}
      - name: Install crusher-cli
        run: npm install -g crusher-cli@1.3.34
      - name: Start crusher tests
        run: crusher-cli run --project_id=112 --base_url=https://${{ env.BRANCH_NAME }}--priceless-hugle-35faad.netlify.app --crusher_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMjgsInRlYW1faWQiOjg1LCJpYXQiOjE2MTM2NjQ4NTEsImV4cCI6NTIxMzY2MTI1MX0.tW5K6CSNHgSyT7Cp9VFPWladbWm_Er-WXHyqt_4r9YQ 

